# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tfx/niba2.0

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tfx/niba2.0

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tfx/niba2.0/CMakeFiles /home/tfx/niba2.0/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tfx/niba2.0/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named niba-server

# Build rule for target.
niba-server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 niba-server
.PHONY : niba-server

# fast build rule for target.
niba-server/fast:
	$(MAKE) -f CMakeFiles/niba-server.dir/build.make CMakeFiles/niba-server.dir/build
.PHONY : niba-server/fast

#=============================================================================
# Target rules for targets named niba-client

# Build rule for target.
niba-client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 niba-client
.PHONY : niba-client

# fast build rule for target.
niba-client/fast:
	$(MAKE) -f CMakeFiles/niba-client.dir/build.make CMakeFiles/niba-client.dir/build
.PHONY : niba-client/fast

client/client_processor.o: client/client_processor.cpp.o

.PHONY : client/client_processor.o

# target to build an object file
client/client_processor.cpp.o:
	$(MAKE) -f CMakeFiles/niba-client.dir/build.make CMakeFiles/niba-client.dir/client/client_processor.cpp.o
.PHONY : client/client_processor.cpp.o

client/client_processor.i: client/client_processor.cpp.i

.PHONY : client/client_processor.i

# target to preprocess a source file
client/client_processor.cpp.i:
	$(MAKE) -f CMakeFiles/niba-client.dir/build.make CMakeFiles/niba-client.dir/client/client_processor.cpp.i
.PHONY : client/client_processor.cpp.i

client/client_processor.s: client/client_processor.cpp.s

.PHONY : client/client_processor.s

# target to generate assembly for a file
client/client_processor.cpp.s:
	$(MAKE) -f CMakeFiles/niba-client.dir/build.make CMakeFiles/niba-client.dir/client/client_processor.cpp.s
.PHONY : client/client_processor.cpp.s

client/client_session.o: client/client_session.cpp.o

.PHONY : client/client_session.o

# target to build an object file
client/client_session.cpp.o:
	$(MAKE) -f CMakeFiles/niba-client.dir/build.make CMakeFiles/niba-client.dir/client/client_session.cpp.o
.PHONY : client/client_session.cpp.o

client/client_session.i: client/client_session.cpp.i

.PHONY : client/client_session.i

# target to preprocess a source file
client/client_session.cpp.i:
	$(MAKE) -f CMakeFiles/niba-client.dir/build.make CMakeFiles/niba-client.dir/client/client_session.cpp.i
.PHONY : client/client_session.cpp.i

client/client_session.s: client/client_session.cpp.s

.PHONY : client/client_session.s

# target to generate assembly for a file
client/client_session.cpp.s:
	$(MAKE) -f CMakeFiles/niba-client.dir/build.make CMakeFiles/niba-client.dir/client/client_session.cpp.s
.PHONY : client/client_session.cpp.s

client/main.o: client/main.cpp.o

.PHONY : client/main.o

# target to build an object file
client/main.cpp.o:
	$(MAKE) -f CMakeFiles/niba-client.dir/build.make CMakeFiles/niba-client.dir/client/main.cpp.o
.PHONY : client/main.cpp.o

client/main.i: client/main.cpp.i

.PHONY : client/main.i

# target to preprocess a source file
client/main.cpp.i:
	$(MAKE) -f CMakeFiles/niba-client.dir/build.make CMakeFiles/niba-client.dir/client/main.cpp.i
.PHONY : client/main.cpp.i

client/main.s: client/main.cpp.s

.PHONY : client/main.s

# target to generate assembly for a file
client/main.cpp.s:
	$(MAKE) -f CMakeFiles/niba-client.dir/build.make CMakeFiles/niba-client.dir/client/main.cpp.s
.PHONY : client/main.cpp.s

server/db_accessor.o: server/db_accessor.cpp.o

.PHONY : server/db_accessor.o

# target to build an object file
server/db_accessor.cpp.o:
	$(MAKE) -f CMakeFiles/niba-server.dir/build.make CMakeFiles/niba-server.dir/server/db_accessor.cpp.o
.PHONY : server/db_accessor.cpp.o

server/db_accessor.i: server/db_accessor.cpp.i

.PHONY : server/db_accessor.i

# target to preprocess a source file
server/db_accessor.cpp.i:
	$(MAKE) -f CMakeFiles/niba-server.dir/build.make CMakeFiles/niba-server.dir/server/db_accessor.cpp.i
.PHONY : server/db_accessor.cpp.i

server/db_accessor.s: server/db_accessor.cpp.s

.PHONY : server/db_accessor.s

# target to generate assembly for a file
server/db_accessor.cpp.s:
	$(MAKE) -f CMakeFiles/niba-server.dir/build.make CMakeFiles/niba-server.dir/server/db_accessor.cpp.s
.PHONY : server/db_accessor.cpp.s

server/logger.o: server/logger.cpp.o

.PHONY : server/logger.o

# target to build an object file
server/logger.cpp.o:
	$(MAKE) -f CMakeFiles/niba-server.dir/build.make CMakeFiles/niba-server.dir/server/logger.cpp.o
.PHONY : server/logger.cpp.o

server/logger.i: server/logger.cpp.i

.PHONY : server/logger.i

# target to preprocess a source file
server/logger.cpp.i:
	$(MAKE) -f CMakeFiles/niba-server.dir/build.make CMakeFiles/niba-server.dir/server/logger.cpp.i
.PHONY : server/logger.cpp.i

server/logger.s: server/logger.cpp.s

.PHONY : server/logger.s

# target to generate assembly for a file
server/logger.cpp.s:
	$(MAKE) -f CMakeFiles/niba-server.dir/build.make CMakeFiles/niba-server.dir/server/logger.cpp.s
.PHONY : server/logger.cpp.s

server/main.o: server/main.cpp.o

.PHONY : server/main.o

# target to build an object file
server/main.cpp.o:
	$(MAKE) -f CMakeFiles/niba-server.dir/build.make CMakeFiles/niba-server.dir/server/main.cpp.o
.PHONY : server/main.cpp.o

server/main.i: server/main.cpp.i

.PHONY : server/main.i

# target to preprocess a source file
server/main.cpp.i:
	$(MAKE) -f CMakeFiles/niba-server.dir/build.make CMakeFiles/niba-server.dir/server/main.cpp.i
.PHONY : server/main.cpp.i

server/main.s: server/main.cpp.s

.PHONY : server/main.s

# target to generate assembly for a file
server/main.cpp.s:
	$(MAKE) -f CMakeFiles/niba-server.dir/build.make CMakeFiles/niba-server.dir/server/main.cpp.s
.PHONY : server/main.cpp.s

server/server_processor.o: server/server_processor.cpp.o

.PHONY : server/server_processor.o

# target to build an object file
server/server_processor.cpp.o:
	$(MAKE) -f CMakeFiles/niba-server.dir/build.make CMakeFiles/niba-server.dir/server/server_processor.cpp.o
.PHONY : server/server_processor.cpp.o

server/server_processor.i: server/server_processor.cpp.i

.PHONY : server/server_processor.i

# target to preprocess a source file
server/server_processor.cpp.i:
	$(MAKE) -f CMakeFiles/niba-server.dir/build.make CMakeFiles/niba-server.dir/server/server_processor.cpp.i
.PHONY : server/server_processor.cpp.i

server/server_processor.s: server/server_processor.cpp.s

.PHONY : server/server_processor.s

# target to generate assembly for a file
server/server_processor.cpp.s:
	$(MAKE) -f CMakeFiles/niba-server.dir/build.make CMakeFiles/niba-server.dir/server/server_processor.cpp.s
.PHONY : server/server_processor.cpp.s

server/server_session.o: server/server_session.cpp.o

.PHONY : server/server_session.o

# target to build an object file
server/server_session.cpp.o:
	$(MAKE) -f CMakeFiles/niba-server.dir/build.make CMakeFiles/niba-server.dir/server/server_session.cpp.o
.PHONY : server/server_session.cpp.o

server/server_session.i: server/server_session.cpp.i

.PHONY : server/server_session.i

# target to preprocess a source file
server/server_session.cpp.i:
	$(MAKE) -f CMakeFiles/niba-server.dir/build.make CMakeFiles/niba-server.dir/server/server_session.cpp.i
.PHONY : server/server_session.cpp.i

server/server_session.s: server/server_session.cpp.s

.PHONY : server/server_session.s

# target to generate assembly for a file
server/server_session.cpp.s:
	$(MAKE) -f CMakeFiles/niba-server.dir/build.make CMakeFiles/niba-server.dir/server/server_session.cpp.s
.PHONY : server/server_session.cpp.s

shared/gamedata.o: shared/gamedata.cpp.o

.PHONY : shared/gamedata.o

# target to build an object file
shared/gamedata.cpp.o:
	$(MAKE) -f CMakeFiles/niba-server.dir/build.make CMakeFiles/niba-server.dir/shared/gamedata.cpp.o
	$(MAKE) -f CMakeFiles/niba-client.dir/build.make CMakeFiles/niba-client.dir/shared/gamedata.cpp.o
.PHONY : shared/gamedata.cpp.o

shared/gamedata.i: shared/gamedata.cpp.i

.PHONY : shared/gamedata.i

# target to preprocess a source file
shared/gamedata.cpp.i:
	$(MAKE) -f CMakeFiles/niba-server.dir/build.make CMakeFiles/niba-server.dir/shared/gamedata.cpp.i
	$(MAKE) -f CMakeFiles/niba-client.dir/build.make CMakeFiles/niba-client.dir/shared/gamedata.cpp.i
.PHONY : shared/gamedata.cpp.i

shared/gamedata.s: shared/gamedata.cpp.s

.PHONY : shared/gamedata.s

# target to generate assembly for a file
shared/gamedata.cpp.s:
	$(MAKE) -f CMakeFiles/niba-server.dir/build.make CMakeFiles/niba-server.dir/shared/gamedata.cpp.s
	$(MAKE) -f CMakeFiles/niba-client.dir/build.make CMakeFiles/niba-client.dir/shared/gamedata.cpp.s
.PHONY : shared/gamedata.cpp.s

shared/message.o: shared/message.cpp.o

.PHONY : shared/message.o

# target to build an object file
shared/message.cpp.o:
	$(MAKE) -f CMakeFiles/niba-server.dir/build.make CMakeFiles/niba-server.dir/shared/message.cpp.o
	$(MAKE) -f CMakeFiles/niba-client.dir/build.make CMakeFiles/niba-client.dir/shared/message.cpp.o
.PHONY : shared/message.cpp.o

shared/message.i: shared/message.cpp.i

.PHONY : shared/message.i

# target to preprocess a source file
shared/message.cpp.i:
	$(MAKE) -f CMakeFiles/niba-server.dir/build.make CMakeFiles/niba-server.dir/shared/message.cpp.i
	$(MAKE) -f CMakeFiles/niba-client.dir/build.make CMakeFiles/niba-client.dir/shared/message.cpp.i
.PHONY : shared/message.cpp.i

shared/message.s: shared/message.cpp.s

.PHONY : shared/message.s

# target to generate assembly for a file
shared/message.cpp.s:
	$(MAKE) -f CMakeFiles/niba-server.dir/build.make CMakeFiles/niba-server.dir/shared/message.cpp.s
	$(MAKE) -f CMakeFiles/niba-client.dir/build.make CMakeFiles/niba-client.dir/shared/message.cpp.s
.PHONY : shared/message.cpp.s

shared/structs.o: shared/structs.cpp.o

.PHONY : shared/structs.o

# target to build an object file
shared/structs.cpp.o:
	$(MAKE) -f CMakeFiles/niba-server.dir/build.make CMakeFiles/niba-server.dir/shared/structs.cpp.o
	$(MAKE) -f CMakeFiles/niba-client.dir/build.make CMakeFiles/niba-client.dir/shared/structs.cpp.o
.PHONY : shared/structs.cpp.o

shared/structs.i: shared/structs.cpp.i

.PHONY : shared/structs.i

# target to preprocess a source file
shared/structs.cpp.i:
	$(MAKE) -f CMakeFiles/niba-server.dir/build.make CMakeFiles/niba-server.dir/shared/structs.cpp.i
	$(MAKE) -f CMakeFiles/niba-client.dir/build.make CMakeFiles/niba-client.dir/shared/structs.cpp.i
.PHONY : shared/structs.cpp.i

shared/structs.s: shared/structs.cpp.s

.PHONY : shared/structs.s

# target to generate assembly for a file
shared/structs.cpp.s:
	$(MAKE) -f CMakeFiles/niba-server.dir/build.make CMakeFiles/niba-server.dir/shared/structs.cpp.s
	$(MAKE) -f CMakeFiles/niba-client.dir/build.make CMakeFiles/niba-client.dir/shared/structs.cpp.s
.PHONY : shared/structs.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... niba-server"
	@echo "... edit_cache"
	@echo "... niba-client"
	@echo "... client/client_processor.o"
	@echo "... client/client_processor.i"
	@echo "... client/client_processor.s"
	@echo "... client/client_session.o"
	@echo "... client/client_session.i"
	@echo "... client/client_session.s"
	@echo "... client/main.o"
	@echo "... client/main.i"
	@echo "... client/main.s"
	@echo "... server/db_accessor.o"
	@echo "... server/db_accessor.i"
	@echo "... server/db_accessor.s"
	@echo "... server/logger.o"
	@echo "... server/logger.i"
	@echo "... server/logger.s"
	@echo "... server/main.o"
	@echo "... server/main.i"
	@echo "... server/main.s"
	@echo "... server/server_processor.o"
	@echo "... server/server_processor.i"
	@echo "... server/server_processor.s"
	@echo "... server/server_session.o"
	@echo "... server/server_session.i"
	@echo "... server/server_session.s"
	@echo "... shared/gamedata.o"
	@echo "... shared/gamedata.i"
	@echo "... shared/gamedata.s"
	@echo "... shared/message.o"
	@echo "... shared/message.i"
	@echo "... shared/message.s"
	@echo "... shared/structs.o"
	@echo "... shared/structs.i"
	@echo "... shared/structs.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

